"""
Step 3 — Hazard Characterization: submodule orchestrator.

Runs all hazard characterization analyses AFTER the base storm catalogs
have been generated by ``main.py``. Requires that main.py has already
completed (catalogs exist in outputs/storm_catalog/).

Usage
-----
    cd <project_root>
    python -m src.03_storm_catalog_generation.hazard_characterization [--all | --module MODULE]

Modules
-------
    compound       Compound event detection (temporal overlap)
    duration       Duration & persistence statistics
    seasonality    Monthly/seasonal climatology
    trends         Mann–Kendall + Sen slope trend analysis
    eva            Univariate POT–GPD extreme value analysis
    dependence     Hs–SSH_total dependence (τ, ρ, χ, χ̄)
    site-export    Unified JSON export for results website
    all            Run everything in order (default)

Prerequisites
-------------
    - Storm catalogs: outputs/storm_catalog/catalog_hs_storms.json
                      outputs/storm_catalog/catalog_ssh_total_storms.json
    - Run metadata:   outputs/storm_catalog/logs/run_metadata.json
    These are produced by ``python -m src.03_storm_catalog_generation.main``.
"""
from __future__ import annotations

import argparse
import importlib
import logging
import sys
import time
from pathlib import Path

from .config import analysis_config as cfg

log = logging.getLogger("step3_hazard")

# Base package for relative imports
_PKG = "src.03_storm_catalog_generation"

MODULES = [
    "compound",
    "duration",
    "seasonality",
    "trends",
    "eva",
    "dependence",
    "site-export",
]


def _import(submodule: str):
    """Import a numbered submodule (can't use normal from-import with digit-prefixed dirs)."""
    return importlib.import_module(f"{_PKG}.{submodule}")


def run_compound():
    """Run compound event detection."""
    mod = _import("02_compound_detection.detection")
    log.info("═" * 60)
    log.info("MODULE: Compound Event Detection")
    log.info("═" * 60)
    results = mod.run_compound_detection()
    mod.save_compound_results(results)
    n = len(results.get("grid_results", []))
    log.info("Compound detection complete: %d grid points", n)


def run_duration():
    """Run duration & persistence statistics."""
    mod = _import("03_duration_persistence.persistence")
    log.info("═" * 60)
    log.info("MODULE: Duration & Persistence")
    log.info("═" * 60)
    results = mod.run_persistence()
    mod.save_persistence_results(results)
    n = len(results.get("grid_results", []))
    log.info("Duration/persistence complete: %d grid points", n)


def run_seasonality():
    """Run monthly/seasonal climatology."""
    mod = _import("04_monthly_seasonality.seasonality")
    log.info("═" * 60)
    log.info("MODULE: Monthly Seasonality")
    log.info("═" * 60)
    results = mod.run_seasonality()
    mod.save_seasonality_results(results)
    n = len(results.get("grid_results", []))
    log.info("Seasonality complete: %d grid points", n)


def run_trends():
    """Run Mann–Kendall trend analysis."""
    mod = _import("05_trends.trends")
    log.info("═" * 60)
    log.info("MODULE: Trend Analysis (Mann–Kendall + Sen slope)")
    log.info("═" * 60)
    results = mod.run_trends()
    mod.save_trend_results(results)
    n = len(results.get("grid_results", []))
    log.info("Trend analysis complete: %d grid points", n)


def run_eva():
    """Run univariate POT-GPD EVA."""
    mod = _import("06_univariate_eva.eva")
    log.info("═" * 60)
    log.info("MODULE: Univariate EVA (POT–GPD)")
    log.info("═" * 60)
    results = mod.run_eva()
    mod.save_eva_results(results)
    n = len(results.get("grid_results", []))
    log.info("EVA complete: %d grid points", n)


def run_dependence():
    """Run Hs–SSH_total dependence analysis."""
    mod = _import("07_dependence.dependence")
    log.info("═" * 60)
    log.info("MODULE: Dependence Analysis (Hs–SSH_total)")
    log.info("═" * 60)
    results = mod.run_dependence()
    mod.save_dependence_results(results)
    n = len(results.get("grid_results", []))
    log.info("Dependence analysis complete: %d grid points", n)


def run_site_export():
    """Run unified site export."""
    mod = _import("08_site_export.export")
    log.info("═" * 60)
    log.info("MODULE: Site Export")
    log.info("═" * 60)
    output = mod.run_site_export()
    mod.save_site_export(output)
    n = len(output.get("grid_points", []))
    log.info("Site export complete: %d grid points", n)


MODULE_RUNNERS = {
    "compound": run_compound,
    "duration": run_duration,
    "seasonality": run_seasonality,
    "trends": run_trends,
    "eva": run_eva,
    "dependence": run_dependence,
    "site-export": run_site_export,
}


def main():
    parser = argparse.ArgumentParser(
        description="Step 3 — Hazard Characterization submodule orchestrator",
    )
    parser.add_argument(
        "--module", "-m",
        choices=MODULES + ["all"],
        default="all",
        help="Which module to run (default: all)",
    )
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    # Check catalogs exist
    from .shared.catalog_utils import HS_CATALOG, SSH_CATALOG, METADATA_FILE
    for path in [HS_CATALOG, SSH_CATALOG, METADATA_FILE]:
        if not path.exists():
            log.error("Required file not found: %s", path)
            log.error("Run 'python -m src.03_storm_catalog_generation.main' first.")
            sys.exit(1)

    t0 = time.perf_counter()

    if args.module == "all":
        modules_to_run = MODULES
    else:
        modules_to_run = [args.module]

    for mod in modules_to_run:
        mt0 = time.perf_counter()
        try:
            MODULE_RUNNERS[mod]()
        except Exception:
            log.exception("Module '%s' failed", mod)
            sys.exit(1)
        elapsed = time.perf_counter() - mt0
        log.info("Module '%s' elapsed: %.1f s", mod, elapsed)

    total = time.perf_counter() - t0
    log.info("All modules completed in %.1f s", total)


if __name__ == "__main__":
    main()
