# -*- coding: utf-8 -*-
"""OSR11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dsKsmxNg-RhM1cpNiJP-rumTB3BLoau8
"""

from google.colab import drive
drive.mount('/content/drive')

pdf_path = "/content/drive/MyDrive/OSR11/municipios.pdf"

!pip install pdfplumber

!pip install pdfplumber pandas openpyxl

"""EXTRAI OS MUNICÍPIOS DO PDF DA CIBELE"""

import pdfplumber
import pandas as pd

pdf_path = "/content/drive/MyDrive/OSR11/municipios.pdf"
excel_path = "/content/drive/MyDrive/OSR11/municipios_extraidos.xlsx"

todas_linhas = []

with pdfplumber.open(pdf_path) as pdf:
    for i, page in enumerate(pdf.pages, start=1):
        tables = page.extract_tables()

        for table in tables:
            for row in table:
                if row:
                    row_limpa = [
                        str(cell).replace("\n", " ").strip() if cell is not None else ""
                        for cell in row
                    ]
                    row_limpa.append(i)  # página de origem
                    todas_linhas.append(row_limpa)

df = pd.DataFrame(todas_linhas)

# salva em Excel
df.to_excel(excel_path, index=False, header=False)

excel_path

"""INSERE O CÓDIGO DO IBGE NO xlsx. de municipios"""

!pip install pandas openpyxl requests unidecode

import pandas as pd
import requests
from unidecode import unidecode

arquivo = "/content/drive/MyDrive/OSR11/municipios_extraidos.xlsx"

df = pd.read_excel(arquivo)

# garantir nomes das colunas
df.columns = ["municipio", "uf"]

def limpar_nome(x):
    return unidecode(str(x).upper().strip())

df["municipio_limpo"] = df["municipio"].apply(limpar_nome)
df["uf"] = df["uf"].astype(str).str.upper().str.strip()

# baixar municípios do IBGE
url = "https://servicodados.ibge.gov.br/api/v1/localidades/municipios"
dados = requests.get(url).json()

ibge = pd.json_normalize(dados)

ibge_base = pd.DataFrame({
    "cod_ibge": ibge["id"].astype(str),
    "municipio_ibge": ibge["nome"],
    "municipio_limpo": ibge["nome"].apply(limpar_nome),
    "uf": ibge["microrregiao.mesorregiao.UF.sigla"]
})

# cruzar por município + UF
resultado = df.merge(
    ibge_base[["cod_ibge", "municipio_limpo", "uf"]],
    on=["municipio_limpo", "uf"],
    how="left"
)

# organizar colunas
resultado = resultado[["municipio", "uf", "cod_ibge"]]

# salvar
saida = "/content/drive/MyDrive/OSR11/municipios_com_codigo_ibge.xlsx"
resultado.to_excel(saida, index=False)

saida

resultado[resultado["cod_ibge"].isna()]

"""SELECIONA AS VARIÁVEIS DO IBGE DO CENSO DE 2022 E INCLUI NO xlsx."""

!pip install pandas openpyxl requests sidrapy

import pandas as pd
from sidrapy import get_table

arquivo = "/content/drive/MyDrive/OSR11/municipios_com_codigo_ibge.xlsx"

df_base = pd.read_excel(arquivo)
df_base["cod_ibge"] = df_base["cod_ibge"].astype(str)

def sidra(tabela):
    df = get_table(
        table_code=str(tabela),
        territorial_level="6",
        ibge_territorial_code="all",
        period="2022"
    )
    df = pd.DataFrame(df)
    df.columns = df.iloc[0]
    df = df.iloc[1:].copy()
    return df

# Baixar tabelas principais
agua = sidra(6909)
lixo = sidra(9541)
ocupacao = sidra(9930)
renda = sidra(10296)

# Essas ainda vamos confirmar/ajustar conforme retorno do SIDRA:
# idade = sidra(XXXX)
# cor_raca = sidra(XXXX)
# alfabetizacao = sidra(XXXX)
# esgoto = sidra(XXXX)
# pavimentacao = sidra(XXXX)

for nome, tabela in {
    "agua": agua,
    "lixo": lixo,
    "ocupacao": ocupacao,
    "renda": renda
}.items():
    print("\n---", nome.upper(), "---")
    print(tabela.columns.tolist())
    print(tabela.head())

categorias = {
    "agua": (agua, "Principal forma de abastecimento de água"),
    "lixo": (lixo, "Destino do lixo"),
    "ocupacao": (ocupacao, "Condição de ocupação do domicílio"),
    "renda": (renda, "Classes de rendimento nominal mensal domiciliar per capita")
}

for nome, (tabela, coluna) in categorias.items():
    print("\n---", nome.upper(), "---")
    print(tabela[coluna].drop_duplicates().to_list())

import sidrapy
help(sidrapy.get_table)

classifications={"codigo_da_classificacao": "categorias"}

!pip install pandas sidrapy openpyxl

import pandas as pd
from sidrapy import get_table

# =========================
# FUNÇÃO SIDRA (SEM CLASSIFICAÇÃO)
# =========================
def sidra(tabela, variavel):
    df = get_table(
        table_code=str(tabela),
        territorial_level="6",
        ibge_territorial_code="all",
        variable=str(variavel),
        period="2022"
    )

    df = pd.DataFrame(df)
    df.columns = df.iloc[0]
    df = df.iloc[1:].copy()

    return df

# =========================
# BAIXAR TABELAS
# =========================
agua = sidra(6909, 382)
lixo = sidra(9541, 382)
ocupacao = sidra(9930, 381)
renda = sidra(10296, 13604)

# =========================
# VER COLUNAS DISPONÍVEIS
# =========================

print("\n--- COLUNAS ÁGUA ---")
print(agua.columns.tolist())

print("\n--- COLUNAS LIXO ---")
print(lixo.columns.tolist())

print("\n--- COLUNAS OCUPAÇÃO ---")
print(ocupacao.columns.tolist())

print("\n--- COLUNAS RENDA ---")
print(renda.columns.tolist())

# descobrir códigos das classificações a partir da própria tabela

for nome, tabela in {
    "agua": agua,
    "lixo": lixo,
    "ocupacao": ocupacao,
    "renda": renda
}.items():
    print("\n---", nome.upper(), "---")

    for col in tabela.columns:
        if "(Código)" in col:
            print(col, "=>", tabela[col].drop_duplicates().head(10).to_list())

import pandas as pd
import requests

# carregar seus municípios
base = pd.read_excel("/content/drive/MyDrive/OSR11/municipios_com_codigo_ibge.xlsx")
codigos = ",".join(base["cod_ibge"].astype(str).tolist())

# URL com filtro
url_agua = f"https://apisidra.ibge.gov.br/values/t/6909/n6/{codigos}/v/382/p/2022/c301/all/c1817/72125/c58/95253/c86/95251?formato=json"

res = requests.get(url_agua)

print(res.status_code)

data = res.json()

agua = pd.DataFrame(data)
agua.columns = agua.iloc[0]
agua = agua.iloc[1:].copy()

print(agua.head())

# categorias
print(agua["Principal forma de abastecimento de água"].drop_duplicates().to_list())

# separar total
total = agua[agua["Principal forma de abastecimento de água"] == "Total"].copy()

# separar rede geral
rede = agua[agua["Principal forma de abastecimento de água"] == "Rede geral de distribuição"].copy()

# merge
df_agua = total.merge(
    rede,
    on="Município (Código)",
    suffixes=("_total", "_rede")
)

# calcular
df_agua["pop_nowater"] = 1 - (
    df_agua["Valor_rede"].astype(float) / df_agua["Valor_total"].astype(float)
)

# ajustar colunas
df_agua = df_agua[["Município (Código)", "pop_nowater"]]
df_agua.columns = ["cod_ibge", "pop_nowater"]

df_agua.head()

import pandas as pd

arquivo = "/content/drive/MyDrive/OSR11/municipios_com_codigo_ibge.xlsx"

base = pd.read_excel(arquivo)
base["cod_ibge"] = base["cod_ibge"].astype(str)

# juntar
base = base.merge(df_agua, on="cod_ibge", how="left")

# salvar (mesmo arquivo)
base.to_excel(arquivo, index=False)

base.head()

"""LIXO"""

import pandas as pd

arquivo = "/content/drive/MyDrive/OSR11/municipios_com_codigo_ibge.xlsx"

base = pd.read_excel(arquivo)

# manter só uma linha por município
base = base.groupby(
    ["municipio", "uf", "cod_ibge", "pop_nowater"],
    as_index=False
).mean(numeric_only=True)

# criar coluna final correta
base["pop_nogarbage"] = base[
    ["pop_nogarbage_x", "pop_nogarbage_y"]
].mean(axis=1)

# apagar colunas duplicadas
base = base.drop(columns=[
    "pop_nogarbage_x",
    "pop_nogarbage_y"
])

# salvar
base.to_excel(arquivo, index=False)

print(base.shape)
base.head()

"""RENDA"""

import pandas as pd
import requests

arquivo = "/content/drive/MyDrive/OSR11/municipios_com_codigo_ibge.xlsx"

# carregar base
base = pd.read_excel(arquivo)
base["cod_ibge"] = base["cod_ibge"].astype(str)

# remover coluna antiga se existir
base = base.drop(columns=["pop_rent"], errors="ignore")

# municípios
codigos = ",".join(base["cod_ibge"].tolist())

# URL SIDRA
url_ocup = f"https://apisidra.ibge.gov.br/values/t/9930/n6/{codigos}/v/381/p/2022/c63/all/c65/95810/c125/2932?formato=json"

res = requests.get(url_ocup)

print(res.status_code)
print(res.text[:300])

# =========================
# PRÓPRIO CORRETO
# =========================
proprio = ocup[
    ocup["Condição de ocupação do domicílio"] == "Próprio de algum morador"
][["Município (Código)", "Valor"]]

proprio = proprio.rename(columns={"Valor": "valor_proprio"})

# =========================
# MERGE
# =========================
df_ocup = total.merge(
    proprio,
    on="Município (Código)",
    how="left"
)

df_ocup["valor_proprio"] = df_ocup["valor_proprio"].fillna(0)

# =========================
# CÁLCULO
# =========================
df_ocup["pop_rent"] = 1 - (
    df_ocup["valor_proprio"] / df_ocup["valor_total"]
)

# =========================
# AJUSTAR
# =========================
df_ocup = df_ocup[["Município (Código)", "pop_rent"]]

df_ocup.columns = ["cod_ibge", "pop_rent"]

df_ocup["cod_ibge"] = df_ocup["cod_ibge"].astype(str)

# =========================
# REMOVER COLUNA ANTIGA
# =========================
base = base.drop(columns=["pop_rent"], errors="ignore")

# =========================
# MERGE FINAL
# =========================
base = base.merge(
    df_ocup,
    on="cod_ibge",
    how="left"
)

# =========================
# SALVAR
# =========================
base.to_excel(arquivo, index=False)

base[["municipio", "pop_rent"]].head()

ocup["Condição de ocupação do domicílio"].drop_duplicates().to_list()

"""PROPRORÇÃO DE POP COM BAIXA RENDA"""

import pandas as pd
import requests

arquivo = "/content/drive/MyDrive/OSR11/municipios_com_codigo_ibge.xlsx"

# =========================
# CARREGAR BASE
# =========================
base = pd.read_excel(arquivo)

base["cod_ibge"] = base["cod_ibge"].astype(str)

# remover coluna antiga
base = base.drop(columns=["pop_poverty"], errors="ignore")

# =========================
# MUNICÍPIOS
# =========================
codigos = ",".join(base["cod_ibge"].tolist())

# =========================
# URL SIDRA
# =========================
url_renda = f"https://apisidra.ibge.gov.br/values/t/10296/n6/{codigos}/v/13604/p/2022/c386/all/c2/6794/c86/95251?formato=json"

res = requests.get(url_renda)

print(res.status_code)

# =========================
# JSON → DATAFRAME
# =========================
data = res.json()

renda = pd.DataFrame(data)

renda.columns = renda.iloc[0]

renda = renda.iloc[1:].copy()

renda["Valor"] = pd.to_numeric(renda["Valor"], errors="coerce")

# =========================
# TOTAL
# =========================
total = renda[
    renda["Classes de rendimento nominal mensal domiciliar per capita"] == "Total"
][["Município (Código)", "Valor"]]

total = total.rename(columns={"Valor": "valor_total"})

# =========================
# BAIXA RENDA
# Até 1/2 salário mínimo
# =========================
baixa = renda[
    renda["Classes de rendimento nominal mensal domiciliar per capita"].isin([
        "Até 1/4 de salário mínimo",
        "Mais de 1/4 a 1/2 salário mínimo"
    ])
]

baixa = baixa.groupby("Município (Código)", as_index=False)["Valor"].sum()

baixa = baixa.rename(columns={"Valor": "valor_baixa"})

# =========================
# MERGE
# =========================
df_renda = total.merge(
    baixa,
    on="Município (Código)",
    how="left"
)

df_renda["valor_baixa"] = df_renda["valor_baixa"].fillna(0)

# =========================
# CÁLCULO
# =========================
df_renda["pop_poverty"] = (
    df_renda["valor_baixa"] / df_renda["valor_total"]
)

# =========================
# AJUSTAR
# =========================
df_renda = df_renda[["Município (Código)", "pop_poverty"]]

df_renda.columns = ["cod_ibge", "pop_poverty"]

df_renda["cod_ibge"] = df_renda["cod_ibge"].astype(str)

# =========================
# MERGE FINAL
# =========================
base = base.merge(
    df_renda,
    on="cod_ibge",
    how="left"
)

# remover duplicados
base = base.drop_duplicates(subset=["cod_ibge"])

# =========================
# SALVAR
# =========================
base.to_excel(arquivo, index=False)

# visualizar
base[["municipio", "pop_poverty"]].head()

"""POP 0-9 e 60+"""

import pandas as pd
import requests

arquivo = "/content/drive/MyDrive/OSR11/municipios_com_codigo_ibge.xlsx"

base = pd.read_excel(arquivo)
base["cod_ibge"] = base["cod_ibge"].astype(str)

base = base.drop(columns=["pop_agevul"], errors="ignore")

codigos = ",".join(base["cod_ibge"].tolist())

url_idade = f"https://apisidra.ibge.gov.br/values/t/9514/n6/{codigos}/v/93/p/2022/c2/6794/c287/6653,49108,49109,60040,60041,93070,93084,93095,93096,93097,93098,100362/c286/113635?formato=json"

res = requests.get(url_idade)
print(res.status_code)

data = res.json()

idade = pd.DataFrame(data)
idade.columns = idade.iloc[0]
idade = idade.iloc[1:].copy()

idade["Valor"] = pd.to_numeric(idade["Valor"], errors="coerce")

total = idade[idade["Idade"] == "Total"][["Município (Código)", "Valor"]]
total = total.rename(columns={"Valor": "valor_total"})

vulneravel = idade[idade["Idade"] != "Total"]
vulneravel = vulneravel.groupby("Município (Código)", as_index=False)["Valor"].sum()
vulneravel = vulneravel.rename(columns={"Valor": "valor_vulneravel"})

df_idade = total.merge(vulneravel, on="Município (Código)", how="left")

df_idade["pop_agevul"] = df_idade["valor_vulneravel"] / df_idade["valor_total"]

df_idade = df_idade[["Município (Código)", "pop_agevul"]]
df_idade.columns = ["cod_ibge", "pop_agevul"]
df_idade["cod_ibge"] = df_idade["cod_ibge"].astype(str)

base = base.merge(df_idade, on="cod_ibge", how="left")
base = base.drop_duplicates(subset=["cod_ibge"])

base.to_excel(arquivo, index=False)

base[["municipio", "pop_agevul"]].head()

base["pop_agevul"].isna().sum()

"""POP BRANCA"""

import pandas as pd
import requests

arquivo = "/content/drive/MyDrive/OSR11/municipios_com_codigo_ibge.xlsx"

base = pd.read_excel(arquivo)
base["cod_ibge"] = base["cod_ibge"].astype(str)

base = base.drop(columns=["pop_nonwhite"], errors="ignore")

codigos = ",".join(base["cod_ibge"].tolist())

url_raca = f"https://apisidra.ibge.gov.br/values/t/9605/n6/{codigos}/v/93/p/2022/c86/2776,95251?formato=json"

res = requests.get(url_raca)

print(res.status_code)

data = res.json()

raca = pd.DataFrame(data)
raca.columns = raca.iloc[0]
raca = raca.iloc[1:].copy()

raca["Valor"] = pd.to_numeric(raca["Valor"], errors="coerce")

# total
total = raca[raca["Cor ou raça"] == "Total"][["Município (Código)", "Valor"]]
total = total.rename(columns={"Valor": "valor_total"})

# branca
branca = raca[raca["Cor ou raça"] == "Branca"][["Município (Código)", "Valor"]]
branca = branca.rename(columns={"Valor": "valor_branca"})

# merge
df_raca = total.merge(branca, on="Município (Código)", how="left")

# cálculo
df_raca["pop_nonwhite"] = 1 - (
    df_raca["valor_branca"] / df_raca["valor_total"]
)

# ajustar
df_raca = df_raca[["Município (Código)", "pop_nonwhite"]]
df_raca.columns = ["cod_ibge", "pop_nonwhite"]

df_raca["cod_ibge"] = df_raca["cod_ibge"].astype(str)

# merge final
base = base.merge(df_raca, on="cod_ibge", how="left")

base = base.drop_duplicates(subset=["cod_ibge"])

# salvar
base.to_excel(arquivo, index=False)

base[["municipio", "pop_nonwhite"]].head()

"""ANALFABETISMO"""

import pandas as pd
import requests

arquivo = "/content/drive/MyDrive/OSR11/municipios_com_codigo_ibge.xlsx"

# carregar base
base = pd.read_excel(arquivo)

base["cod_ibge"] = base["cod_ibge"].astype(str)

# remover antiga
base = base.drop(columns=["pop_illiterate"], errors="ignore")

# municípios
codigos = ",".join(base["cod_ibge"].tolist())

# URL alfabetização
url_alf = f"https://apisidra.ibge.gov.br/values/t/9543/n6/{codigos}/v/2513/p/2022/c2/6794/c86/95251/c287/100362?formato=json"

res = requests.get(url_alf)

print(res.status_code)

data = res.json()

alf = pd.DataFrame(data)

alf.columns = alf.iloc[0]

alf = alf.iloc[1:].copy()

alf["Valor"] = pd.to_numeric(alf["Valor"], errors="coerce")

# taxa analfabetismo
alf["pop_illiterate"] = 1 - (alf["Valor"] / 100)

# ajustar
df_alf = alf[["Município (Código)", "pop_illiterate"]]

df_alf.columns = ["cod_ibge", "pop_illiterate"]

df_alf["cod_ibge"] = df_alf["cod_ibge"].astype(str)

# merge
base = base.merge(df_alf, on="cod_ibge", how="left")

base = base.drop_duplicates(subset=["cod_ibge"])

# salvar
base.to_excel(arquivo, index=False)

base[["municipio", "pop_illiterate"]].head()

"""população sem esgotamento sanitário adequado"""

# =========================
# ADEQUADO CORRETO
# =========================

adequado = esgoto[
    esgoto["Tipo de esgotamento sanitário"].isin([
        "Rede geral ou pluvial",
        "Fossa séptica ou fossa filtro ligada à rede"
    ])
]

adequado = adequado.groupby(
    "Município (Código)",
    as_index=False
)["Valor"].sum()

adequado = adequado.rename(columns={"Valor": "valor_adequado"})


# =========================
# MERGE
# =========================

df_esgoto = total.merge(
    adequado,
    on="Município (Código)",
    how="left"
)

df_esgoto["valor_adequado"] = df_esgoto["valor_adequado"].fillna(0)


# =========================
# CÁLCULO
# =========================

df_esgoto["pop_nosewage"] = 1 - (
    df_esgoto["valor_adequado"] / df_esgoto["valor_total"]
)

# ajustar
df_esgoto = df_esgoto[["Município (Código)", "pop_nosewage"]]

df_esgoto.columns = ["cod_ibge", "pop_nosewage"]

df_esgoto["cod_ibge"] = df_esgoto["cod_ibge"].astype(str)

# remover antiga
base = base.drop(columns=["pop_nosewage"], errors="ignore")

# merge final
base = base.merge(df_esgoto, on="cod_ibge", how="left")

base = base.drop_duplicates(subset=["cod_ibge"])

# salvar
base.to_excel(arquivo, index=False)

base[["municipio", "pop_nosewage"]].head()

esgoto["Tipo de esgotamento sanitário"].drop_duplicates().to_list()

"""PAVIMENTAÇÃO"""

import pandas as pd
import requests

arquivo = "/content/drive/MyDrive/OSR11/municipios_com_codigo_ibge.xlsx"

base = pd.read_excel(arquivo)
base["cod_ibge"] = base["cod_ibge"].astype(str)

base = base.drop(columns=["pop_nopaving"], errors="ignore")

codigos = ",".join(base["cod_ibge"].tolist())

url_pav = f"https://apisidra.ibge.gov.br/values/t/6591/n6/{codigos}/v/allxp/p/2022/c2/6794/c58/95253/c14/200,72246,72247?formato=json"

res = requests.get(url_pav)

print(res.status_code)
print(res.text[:300])

data = res.json()

pav = pd.DataFrame(data)
pav.columns = pav.iloc[0]
pav = pav.iloc[1:].copy()

pav["Valor"] = pd.to_numeric(pav["Valor"], errors="coerce")

print(pav["Características do entorno"].drop_duplicates().to_list())
print(pav["Variável"].drop_duplicates().to_list())

pav["Valor"] = pd.to_numeric(pav["Valor"], errors="coerce")

total = pav[
    pav["Características do entorno"] == "Total"
][["Município (Código)", "Valor"]].rename(columns={"Valor": "valor_total"})

nopav = pav[
    pav["Características do entorno"] == "Via pavimentada - Não existe"
][["Município (Código)", "Valor"]].rename(columns={"Valor": "valor_nopav"})

df_pav = total.merge(nopav, on="Município (Código)", how="left")
df_pav["valor_nopav"] = df_pav["valor_nopav"].fillna(0)

df_pav["pop_nopaving"] = df_pav["valor_nopav"] / df_pav["valor_total"]

df_pav = df_pav[["Município (Código)", "pop_nopaving"]]
df_pav.columns = ["cod_ibge", "pop_nopaving"]
df_pav["cod_ibge"] = df_pav["cod_ibge"].astype(str)

base = base.merge(df_pav, on="cod_ibge", how="left")
base = base.drop_duplicates(subset=["cod_ibge"])

base.to_excel(arquivo, index=False)

base[["municipio", "pop_nopaving"]].head()

"""MÉDIA DE MORADOR POR DOMICÍLIO"""

import pandas as pd
import requests

arquivo = "/content/drive/MyDrive/OSR11/municipios_com_codigo_ibge.xlsx"

base = pd.read_excel(arquivo)
base["cod_ibge"] = base["cod_ibge"].astype(str)

base = base.drop(columns=["pop_house"], errors="ignore")

codigos = ",".join(base["cod_ibge"].tolist())

# população total por município
url_pop = f"https://apisidra.ibge.gov.br/values/t/9605/n6/{codigos}/v/93/p/2022/c86/95251?formato=json"

res_pop = requests.get(url_pop)
print(res_pop.status_code)

pop = pd.DataFrame(res_pop.json())
pop.columns = pop.iloc[0]
pop = pop.iloc[1:].copy()
pop["Valor"] = pd.to_numeric(pop["Valor"], errors="coerce")

pop = pop[["Município (Código)", "Valor"]]
pop = pop.rename(columns={"Valor": "pop_total"})

# domicílios ocupados
url_dom = f"https://apisidra.ibge.gov.br/values/t/9930/n6/{codigos}/v/381/p/2022/c63/95826/c65/95810/c125/2932?formato=json"

res_dom = requests.get(url_dom)
print(res_dom.status_code)

dom = pd.DataFrame(res_dom.json())
dom.columns = dom.iloc[0]
dom = dom.iloc[1:].copy()
dom["Valor"] = pd.to_numeric(dom["Valor"], errors="coerce")

dom = dom[["Município (Código)", "Valor"]]
dom = dom.rename(columns={"Valor": "dom_total"})

df_house = pop.merge(dom, on="Município (Código)", how="left")

df_house["pop_house"] = df_house["pop_total"] / df_house["dom_total"]

df_house = df_house[["Município (Código)", "pop_house"]]
df_house.columns = ["cod_ibge", "pop_house"]
df_house["cod_ibge"] = df_house["cod_ibge"].astype(str)

base = base.merge(df_house, on="cod_ibge", how="left")
base = base.drop_duplicates(subset=["cod_ibge"])

base.to_excel(arquivo, index=False)

base[["municipio", "pop_house"]].head()

import pandas as pd

arquivo = "/content/drive/MyDrive/OSR11/municipios_com_codigo_ibge.xlsx"

# carregar base
base = pd.read_excel(arquivo)

# normalizar pop_house entre 0 e 1
base["pop_house"] = (
    (base["pop_house"] - base["pop_house"].min()) /
    (base["pop_house"].max() - base["pop_house"].min())
)

# salvar
base.to_excel(arquivo, index=False)

# visualizar
base[["municipio", "pop_house"]].head()

"""
Isso vai:

verificar se ainda existe valor vazio
padronizar todas as variáveis para média 0 e desvio 1
preparar a matriz para o PCA"""

import pandas as pd
from sklearn.preprocessing import StandardScaler

arquivo = "/content/drive/MyDrive/OSR11/municipios_com_codigo_ibge.xlsx"

base = pd.read_excel(arquivo)

variaveis = [
    "pop_house",
    "pop_rent",
    "pop_poverty",
    "pop_agevul",
    "pop_nonwhite",
    "pop_illiterate",
    "pop_nowater",
    "pop_nosewage",
    "pop_nogarbage",
    "pop_nopaving"
]

# conferir missing
print(base[variaveis].isna().sum())

# padronização z-score
scaler = StandardScaler()

X_scaled = scaler.fit_transform(base[variaveis])

# dataframe padronizado
df_scaled = pd.DataFrame(
    X_scaled,
    columns=variaveis
)

df_scaled.head()

"""PCA"""

from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np

# PCA
pca = PCA()

X_pca = pca.fit_transform(X_scaled)

# variância explicada
explained = pca.explained_variance_ratio_

for i, var in enumerate(explained, start=1):
    print(f"PC{i}: {var*100:.2f}%")

"""RODANDO PARA PCA1"""

from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np

# =========================
# PCA
# =========================

pca = PCA(n_components=1)

PC1 = pca.fit_transform(X_scaled)

# adicionar na base
base["PC1"] = PC1

# =========================
# GARANTIR POLARIDADE
# maior valor = maior vulnerabilidade
# =========================

corr_media = np.mean([
    np.corrcoef(base["PC1"], base[v])[0,1]
    for v in variaveis
])

if corr_media < 0:
    base["PC1"] = base["PC1"] * -1

# =========================
# NORMALIZAR 0–100
# =========================

scaler = MinMaxScaler(feature_range=(0,100))

base["SVI_Coast_2022"] = scaler.fit_transform(
    base[["PC1"]]
)

# =========================
# RESULTADO
# =========================

ranking = base[
    ["municipio", "uf", "SVI_Coast_2022"]
].sort_values(
    "SVI_Coast_2022",
    ascending=False
)

print(ranking.head(20))

arquivo = "/content/drive/MyDrive/OSR11/municipios_com_codigo_ibge.xlsx"

base.to_excel(arquivo, index=False)

print("SVI_Coast_2022 salvo no mesmo arquivo!")

"""BALNEÁRIO RINCÃO"""

import pandas as pd

arquivo = "/content/drive/MyDrive/OSR11/municipios_com_codigo_ibge-versaofinal-comindice.xlsx"

base = pd.read_excel(arquivo)

# remover linhas antigas se já existir
base = base[~base["municipio"].astype(str).str.upper().str.contains("BALNEÁRIO RINCÃO|BALNEARIO RINCAO", na=False)]

# adicionar Balneário Rincão
nova_linha = {
    "municipio": "BALNEÁRIO RINCÃO",
    "uf": "SC",
    "cod_ibge": "4220000",
    "COD_MUN": "4220000"
}

base = pd.concat([base, pd.DataFrame([nova_linha])], ignore_index=True)

# salvar temporário
saida = "/content/drive/MyDrive/OSR11/base_com_balneario_rincao.xlsx"
base.to_excel(saida, index=False)

print("Linhas:", len(base))
base.tail()

import pandas as pd
import requests

arquivo = "/content/drive/MyDrive/OSR11/municipios_com_codigo_ibge-versaofinal-comindice.xlsx"

base = pd.read_excel(arquivo)

base["CD_MUN"] = base["CD_MUN"].astype(str)

cod = "4220000"  # Balneário Rincão

def sidra_url(url):
    r = requests.get(url)
    print(r.status_code)
    data = r.json()

    df = pd.DataFrame(data)

    df.columns = df.iloc[0]

    df = df.iloc[1:].copy()

    df["Valor"] = pd.to_numeric(df["Valor"], errors="coerce")

    return df

print("Pronto.")

print(base.columns)

# =========================
# BALNEÁRIO RINCÃO - 10 VARIÁVEIS SVI
# =========================

cod = "4220000"

valores = {}

# 1. ÁGUA - pop_nowater
agua = sidra_url(
    f"https://apisidra.ibge.gov.br/values/t/6909/n6/{cod}/v/382/p/2022/c301/all/c1817/72125/c58/95253/c86/95251?formato=json"
)

total = agua[agua["Principal forma de abastecimento de água"] == "Total"]["Valor"].iloc[0]
rede = agua[agua["Principal forma de abastecimento de água"] == "Rede geral de distribuição"]["Valor"].iloc[0]

valores["pop_nowater"] = 1 - (rede / total)


# 2. LIXO - pop_nogarbage
lixo = sidra_url(
    f"https://apisidra.ibge.gov.br/values/t/9541/n6/{cod}/v/382/p/2022/c67/all/c58/95253/c86/95251?formato=json"
)

total = lixo[lixo["Destino do lixo"] == "Total"]["Valor"].iloc[0]
coleta = lixo[lixo["Destino do lixo"].str.contains("Coletado", case=False, na=False)]["Valor"].sum()

valores["pop_nogarbage"] = 1 - (coleta / total)


# 3. OCUPAÇÃO - pop_rent
ocup = sidra_url(
    f"https://apisidra.ibge.gov.br/values/t/9930/n6/{cod}/v/381/p/2022/c63/all/c65/95810/c125/2932?formato=json"
)

total = ocup[ocup["Condição de ocupação do domicílio"] == "Total"]["Valor"].iloc[0]
proprio = ocup[ocup["Condição de ocupação do domicílio"] == "Próprio de algum morador"]["Valor"].iloc[0]

valores["pop_rent"] = 1 - (proprio / total)


# 4. RENDA - pop_poverty
renda = sidra_url(
    f"https://apisidra.ibge.gov.br/values/t/10296/n6/{cod}/v/13604/p/2022/c386/all/c2/6794/c86/95251?formato=json"
)

total = renda[renda["Classes de rendimento nominal mensal domiciliar per capita"] == "Total"]["Valor"].iloc[0]

baixa = renda[
    renda["Classes de rendimento nominal mensal domiciliar per capita"].isin([
        "Até 1/4 de salário mínimo",
        "Mais de 1/4 a 1/2 salário mínimo"
    ])
]["Valor"].sum()

valores["pop_poverty"] = baixa / total


# 5. IDADE VULNERÁVEL - pop_agevul
idade = sidra_url(
    f"https://apisidra.ibge.gov.br/values/t/9514/n6/{cod}/v/93/p/2022/c2/6794/c287/6653,49108,49109,60040,60041,93070,93084,93095,93096,93097,93098,100362/c286/113635?formato=json"
)

total = idade[idade["Idade"] == "Total"]["Valor"].iloc[0]
vulneravel = idade[idade["Idade"] != "Total"]["Valor"].sum()

valores["pop_agevul"] = vulneravel / total


# 6. POPULAÇÃO NÃO BRANCA - pop_nonwhite
raca = sidra_url(
    f"https://apisidra.ibge.gov.br/values/t/9605/n6/{cod}/v/93/p/2022/c86/2776,95251?formato=json"
)

total = raca[raca["Cor ou raça"] == "Total"]["Valor"].iloc[0]
branca = raca[raca["Cor ou raça"] == "Branca"]["Valor"].iloc[0]

valores["pop_nonwhite"] = 1 - (branca / total)


# 7. ANALFABETISMO - pop_illiterate
alf = sidra_url(
    f"https://apisidra.ibge.gov.br/values/t/9543/n6/{cod}/v/2513/p/2022/c2/6794/c86/95251/c287/100362?formato=json"
)

taxa_alf = alf["Valor"].iloc[0]

valores["pop_illiterate"] = 1 - (taxa_alf / 100)


# 8. ESGOTO - pop_nosewage
esgoto = sidra_url(
    f"https://apisidra.ibge.gov.br/values/t/9397/n6/{cod}/v/382/p/2022/c458/72117/c11558/46290,46292,72110,72111,72112,72113,72114,92858/c58/95253/c86/95251?formato=json"
)

total = esgoto[esgoto["Tipo de esgotamento sanitário"] == "Total"]["Valor"].iloc[0]

adequado = esgoto[
    esgoto["Tipo de esgotamento sanitário"].isin([
        "Rede geral ou pluvial",
        "Fossa séptica ou fossa filtro ligada à rede"
    ])
]["Valor"].sum()

valores["pop_nosewage"] = 1 - (adequado / total)


# 9. PAVIMENTAÇÃO - pop_nopaving
pav = sidra_url(
    f"https://apisidra.ibge.gov.br/values/t/6591/n6/{cod}/v/allxp/p/2022/c2/6794/c58/95253/c14/200,72246,72247?formato=json"
)

total = pav[pav["Características do entorno"] == "Total"]["Valor"].iloc[0]
sem_pav = pav[pav["Características do entorno"] == "Via pavimentada - Não existe"]["Valor"].iloc[0]

valores["pop_nopaving"] = sem_pav / total


# 10. POP_HOUSE - média moradores por domicílio
pop = sidra_url(
    f"https://apisidra.ibge.gov.br/values/t/9605/n6/{cod}/v/93/p/2022/c86/95251?formato=json"
)

pop_total = pop["Valor"].iloc[0]

dom = sidra_url(
    f"https://apisidra.ibge.gov.br/values/t/9930/n6/{cod}/v/381/p/2022/c63/95826/c65/95810/c125/2932?formato=json"
)

dom_total = dom["Valor"].iloc[0]

valores["pop_house_raw"] = pop_total / dom_total


# mostrar valores
valores

lixo = sidra_url(
    f"https://apisidra.ibge.gov.br/values/t/9541/n6/{cod}/v/382/p/2022/c67/all/c58/95253/c86/95251?formato=json"
)

print(lixo[[
    "Destino do lixo",
    "Valor"
]])

total = lixo[lixo["Destino do lixo"] == "Total"]["Valor"].iloc[0]
coletado = lixo[lixo["Destino do lixo"] == "Coletado"]["Valor"].iloc[0]

valores["pop_nogarbage"] = 1 - (coletado / total)

valores["pop_nogarbage"]

base[base["municipio"].astype(str).str.contains("RINC", case=False, na=False)]

nova_linha = {
    "municipio": "BALNEÁRIO RINCÃO",
    "uf": "SC",
    "CD_MUN": "4220000",
    "pop_nowater": 0.12508608276466537,
    "pop_nogarbage": 0.002629437175233229,
    "pop_rent": 0.23947051744885683,
    "pop_poverty": 0.13754156993160568,
    "pop_agevul": 0.35216819973718794,
    "pop_nonwhite": 0.17946311244602964,
    "pop_illiterate": 0.0344,
    "pop_nosewage": 0.9599949915482376,
    "pop_nopaving": 0.30680522113800535,
    "pop_house": 2.747292418772563
}

base = pd.concat([base, pd.DataFrame([nova_linha])], ignore_index=True)

print(len(base))
base.tail()

from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.decomposition import PCA
import numpy as np

variaveis = [
    "pop_house",
    "pop_rent",
    "pop_poverty",
    "pop_agevul",
    "pop_nonwhite",
    "pop_illiterate",
    "pop_nowater",
    "pop_nosewage",
    "pop_nogarbage",
    "pop_nopaving"
]

# =========================
# PADRONIZAÇÃO
# =========================

X = base[variaveis].copy()

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

# =========================
# PCA
# =========================

pca = PCA(n_components=1)

PC1 = pca.fit_transform(X_scaled)

base["PC1"] = PC1

# =========================
# AJUSTAR SINAL
# =========================

corr_media = np.mean([
    np.corrcoef(base["PC1"], base[v])[0,1]
    for v in variaveis
])

if corr_media < 0:
    base["PC1"] = base["PC1"] * -1

# =========================
# NORMALIZAR 0–100
# =========================

scaler_final = MinMaxScaler(feature_range=(0,100))

base["SVI_Coast_2022"] = scaler_final.fit_transform(
    base[["PC1"]]
)

# =========================
# VER BALNEÁRIO RINCÃO
# =========================

base[
    base["municipio"].astype(str).str.contains("RINC", case=False, na=False)
][[
    "municipio",
    "SVI_Coast_2022",
    "PC1"
]]

arquivo_final = "/content/drive/MyDrive/OSR11/municipios_com_codigo_ibge-versaofinal-comindice.xlsx"

base.to_excel(arquivo_final, index=False)

print("Base atualizada com Balneário Rincão salva com sucesso.")

print(
    base["pop_house"].min(),
    base["pop_house"].max()
)

from sklearn.preprocessing import MinMaxScaler

scaler_house = MinMaxScaler(feature_range=(0,1))

base["pop_house"] = scaler_house.fit_transform(
    base[["pop_house"]]
)

print(base["pop_house"].min(), base["pop_house"].max())

from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.decomposition import PCA
import numpy as np

variaveis = [
    "pop_house",
    "pop_rent",
    "pop_poverty",
    "pop_agevul",
    "pop_nonwhite",
    "pop_illiterate",
    "pop_nowater",
    "pop_nosewage",
    "pop_nogarbage",
    "pop_nopaving"
]

# =========================
# PADRONIZAÇÃO
# =========================

X = base[variaveis].copy()

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

# =========================
# PCA
# =========================

pca = PCA(n_components=1)

PC1 = pca.fit_transform(X_scaled)

base["PC1"] = PC1

# =========================
# AJUSTAR SINAL
# =========================

corr_media = np.mean([
    np.corrcoef(base["PC1"], base[v])[0,1]
    for v in variaveis
])

if corr_media < 0:
    base["PC1"] = base["PC1"] * -1

# =========================
# NORMALIZAR 0–100
# =========================

scaler_final = MinMaxScaler(feature_range=(0,100))

base["SVI_Coast_2022"] = scaler_final.fit_transform(
    base[["PC1"]]
)

# =========================
# VER BALNEÁRIO RINCÃO
# =========================

base[
    base["municipio"].astype(str).str.contains("RINC", case=False, na=False)
][[
    "municipio",
    "SVI_Coast_2022",
    "PC1",
    "pop_house"
]]

print(pop_total)
print(dom_total)
print(pop_total / dom_total)

base["pop_house"].describe()

base.sort_values("pop_house", ascending=False)[[
    "municipio",
    "pop_house"
]].head(10)

base_sem_rincao = base[
    base["municipio"] != "BALNEÁRIO RINCÃO"
]

print(
    base_sem_rincao["pop_house"].min(),
    base_sem_rincao["pop_house"].max()
)

import pandas as pd
import requests
import numpy as np

from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.decomposition import PCA

# =========================
# 1. CARREGAR BASE
# =========================

arquivo = "/content/drive/MyDrive/OSR11/municipios_com_codigo_ibge-versaofinal-comindice.xlsx"

base = pd.read_excel(arquivo)
base["CD_MUN"] = base["CD_MUN"].astype(str)

codigos = ",".join(base["CD_MUN"].tolist())

# =========================
# 2. FUNÇÃO SIDRA
# =========================

def baixar_sidra(url):
    r = requests.get(url)
    print(r.status_code)
    data = r.json()

    df = pd.DataFrame(data)
    df.columns = df.iloc[0]
    df = df.iloc[1:].copy()
    df["Valor"] = pd.to_numeric(df["Valor"], errors="coerce")

    return df

# =========================
# 3. POPULAÇÃO TOTAL
# =========================

url_pop = f"https://apisidra.ibge.gov.br/values/t/9605/n6/{codigos}/v/93/p/2022/c86/95251?formato=json"

pop = baixar_sidra(url_pop)

pop = pop[["Município (Código)", "Valor"]]
pop = pop.rename(columns={"Município (Código)": "CD_MUN", "Valor": "pop_total"})
pop["CD_MUN"] = pop["CD_MUN"].astype(str)

# =========================
# 4. DOMICÍLIOS TOTAIS
# =========================

url_dom = f"https://apisidra.ibge.gov.br/values/t/9930/n6/{codigos}/v/381/p/2022/c63/95826/c65/95810/c125/2932?formato=json"

dom = baixar_sidra(url_dom)

dom = dom[["Município (Código)", "Valor"]]
dom = dom.rename(columns={"Município (Código)": "CD_MUN", "Valor": "dom_total"})
dom["CD_MUN"] = dom["CD_MUN"].astype(str)

# =========================
# 5. CALCULAR POP_HOUSE BRUTO
# =========================

house = pop.merge(dom, on="CD_MUN", how="left")

house["pop_house_raw"] = house["pop_total"] / house["dom_total"]

# =========================
# 6. JUNTAR NA BASE
# =========================

base = base.drop(columns=["pop_house", "pop_house_raw"], errors="ignore")

base = base.merge(
    house[["CD_MUN", "pop_house_raw"]],
    on="CD_MUN",
    how="left"
)

# =========================
# 7. NORMALIZAR POP_HOUSE 0–1
# =========================

scaler_house = MinMaxScaler(feature_range=(0, 1))

base["pop_house"] = scaler_house.fit_transform(
    base[["pop_house_raw"]]
)

# =========================
# 8. RECALCULAR PCA E SVI
# =========================

variaveis = [
    "pop_house",
    "pop_rent",
    "pop_poverty",
    "pop_agevul",
    "pop_nonwhite",
    "pop_illiterate",
    "pop_nowater",
    "pop_nosewage",
    "pop_nogarbage",
    "pop_nopaving"
]

X = base[variaveis].copy()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=1)
PC1 = pca.fit_transform(X_scaled)

base["PC1"] = PC1

# garantir que maior PC1 = maior vulnerabilidade
corr_media = np.mean([
    np.corrcoef(base["PC1"], base[v])[0, 1]
    for v in variaveis
])

if corr_media < 0:
    base["PC1"] = base["PC1"] * -1

scaler_final = MinMaxScaler(feature_range=(0, 100))

base["SVI_Coast_2022"] = scaler_final.fit_transform(
    base[["PC1"]]
)

# =========================
# 9. CONFERIR BALNEÁRIO RINCÃO
# =========================

print(
    base[
        base["municipio"].astype(str).str.contains("RINC", case=False, na=False)
    ][[
        "municipio",
        "pop_house_raw",
        "pop_house",
        "PC1",
        "SVI_Coast_2022"
    ]]
)

# =========================
# 10. SALVAR
# =========================

base.to_excel(arquivo, index=False)

print("Arquivo atualizado e salvo com sucesso.")