export const tsEvents = [
  { label: "Araquari — 17 Dez 2017", file: "fig_TS_event_051_araquari_20171217.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Araranguá — 28 Mar 2004", file: "fig_TS_event_009_ararangua_20040328.png", sector: "South", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Arroio do Silva — 28 Mar 2004", file: "fig_TS_event_009_balneario_arroio_do_silva_20040328.png", sector: "South", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Barra do Sul — 06 Mai 2001", file: "fig_TS_event_005_balneario_barra_do_sul_20010506.png", sector: "North", isConcurrentSsh: true, isConcurrentTotal: false, detectionChange: "lost" },
  { label: "Balneário Barra do Sul — 28 Mai 2010", file: "fig_TS_event_015_balneario_barra_do_sul_20100528.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Barra do Sul — 27 Jan 2012", file: "fig_TS_event_028_balneario_barra_do_sul_20120127.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Barra do Sul — 27 Jul 2015", file: "fig_TS_event_029_balneario_barra_do_sul_20150727.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Barra do Sul — 18 Ago 2015", file: "fig_TS_event_030_balneario_barra_do_sul_20150818.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Barra do Sul — 01 Jul 2016", file: "fig_TS_event_031_balneario_barra_do_sul_20160701.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Barra do Sul — 12 Dez 2016", file: "fig_TS_event_034_balneario_barra_do_sul_20161212.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Barra do Sul — 25 Mar 2017", file: "fig_TS_event_035_balneario_barra_do_sul_20170325.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Barra do Sul — 02 Mai 2017", file: "fig_TS_event_036_balneario_barra_do_sul_20170502.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Barra do Sul — 21 Mai 2017", file: "fig_TS_event_037_balneario_barra_do_sul_20170521.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Barra do Sul — 26 Ago 2017", file: "fig_TS_event_040_balneario_barra_do_sul_20170826.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Barra do Sul — 09 Set 2017", file: "fig_TS_event_042_balneario_barra_do_sul_20170909.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Barra do Sul — 18 Set 2017", file: "fig_TS_event_045_balneario_barra_do_sul_20170918.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Barra do Sul — 07 Jul 2018", file: "fig_TS_event_055_balneario_barra_do_sul_20180707.png", sector: "North", isConcurrentSsh: true, isConcurrentTotal: true, detectionChange: "maintained" },
  { label: "Balneário Barra do Sul — 03 Dez 2018", file: "fig_TS_event_060_balneario_barra_do_sul_20181203.png", sector: "North", isConcurrentSsh: true, isConcurrentTotal: true, detectionChange: "maintained" },
  { label: "Balneário Barra do Sul — 27 Mar 2019", file: "fig_TS_event_062_balneario_barra_do_sul_20190327.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Barra do Sul — 13 Jun 2019", file: "fig_TS_event_063_balneario_barra_do_sul_20190613.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Barra do Sul — 29 Jul 2019", file: "fig_TS_event_066_balneario_barra_do_sul_20190729.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Barra do Sul — 08 Abr 2020", file: "fig_TS_event_074_balneario_barra_do_sul_20200408.png", sector: "South", isConcurrentSsh: true, isConcurrentTotal: false, detectionChange: "lost" },
  { label: "Balneário Barra do Sul — 30 Jun 2020", file: "fig_TS_event_079_balneario_barra_do_sul_20200630.png", sector: "North", isConcurrentSsh: true, isConcurrentTotal: true, detectionChange: "maintained" },
  { label: "Balneário Camboriú — 05 Mai 2001", file: "fig_TS_event_004_balneario_camboriu_20010505.png", sector: "North", isConcurrentSsh: true, isConcurrentTotal: false, detectionChange: "lost" },
  { label: "Balneário Camboriú — 21 Set 2002", file: "fig_TS_event_007_balneario_camboriu_20020921.png", sector: "Central-north", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Camboriú — 18 Set 2018", file: "fig_TS_event_056_balneario_camboriu_20180918.png", sector: "Central-north", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Camboriú — 21 Mar 2019", file: "fig_TS_event_061_balneario_camboriu_20190321.png", sector: "North", isConcurrentSsh: true, isConcurrentTotal: false, detectionChange: "lost" },
  { label: "Balneário Camboriú — 03 Mar 2020", file: "fig_TS_event_072_balneario_camboriu_20200303.png", sector: "Central-north", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Camboriú — 07 Mai 2020", file: "fig_TS_event_077_balneario_camboriu_20200507.png", sector: "Central-north", isConcurrentSsh: true, isConcurrentTotal: false, detectionChange: "lost" },
  { label: "Balneário Gaivota — 28 Mar 2004", file: "fig_TS_event_009_balneario_gaivota_20040328.png", sector: "South", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Piçarras — 19 Set 1998", file: "fig_TS_event_002_balneario_picarras_19980919.png", sector: "Central-north", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Piçarras — 23 Set 2010", file: "fig_TS_event_020_balneario_picarras_20100923.png", sector: "Central-north", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Piçarras — 23 Jan 2011", file: "fig_TS_event_024_balneario_picarras_20110123.png", sector: "Central-north", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Piçarras — 22 Jul 2019", file: "fig_TS_event_065_balneario_picarras_20190722.png", sector: "Central-north", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Balneário Rincão — 03 Abr 2020", file: "fig_TS_event_073_balneario_rincao_20200403.png", sector: "Central-north", isConcurrentSsh: true, isConcurrentTotal: true, detectionChange: "maintained" },
  { label: "Balneário Rincão — 08 Abr 2020", file: "fig_TS_event_074_balneario_rincao_20200408.png", sector: "South", isConcurrentSsh: true, isConcurrentTotal: false, detectionChange: "lost" },
  { label: "Barra Velha — 06 Mai 2001", file: "fig_TS_event_005_barra_velha_20010506.png", sector: "North", isConcurrentSsh: true, isConcurrentTotal: false, detectionChange: "lost" },
  { label: "Barra Velha — 22 Mai 2001", file: "fig_TS_event_006_barra_velha_20010522.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Barra Velha — 09 Ago 2005", file: "fig_TS_event_011_barra_velha_20050809.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Barra Velha — 13 Mai 2010", file: "fig_TS_event_014_barra_velha_20100513.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Barra Velha — 29 Mai 2011", file: "fig_TS_event_026_barra_velha_20110529.png", sector: "North", isConcurrentSsh: true, isConcurrentTotal: true, detectionChange: "maintained" },
  { label: "Barra Velha — 22 Mai 2017", file: "fig_TS_event_038_barra_velha_20170522.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Barra Velha — 13 Set 2017", file: "fig_TS_event_043_barra_velha_20170913.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Barra Velha — 22 Mar 2019", file: "fig_TS_event_061_barra_velha_20190322.png", sector: "North", isConcurrentSsh: true, isConcurrentTotal: false, detectionChange: "lost" },
  { label: "Barra Velha — 12 Abr 2020", file: "fig_TS_event_076_barra_velha_20200412.png", sector: "North", isConcurrentSsh: true, isConcurrentTotal: false, detectionChange: "lost" },
  { label: "Bombinhas — 06 Mai 2001", file: "fig_TS_event_005_bombinhas_20010506.png", sector: "North", isConcurrentSsh: true, isConcurrentTotal: false, detectionChange: "lost" },
  { label: "Bombinhas — 09 Ago 2005", file: "fig_TS_event_011_bombinhas_20050809.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Bombinhas — 28 Set 2010", file: "fig_TS_event_021_bombinhas_20100928.png", sector: "Central-north", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Bombinhas — 10 Dez 2017", file: "fig_TS_event_049_bombinhas_20171210.png", sector: "Central-north", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Bombinhas — 30 Jun 2020", file: "fig_TS_event_078_bombinhas_20200630.png", sector: "Central-north", isConcurrentSsh: true, isConcurrentTotal: true, detectionChange: "maintained" },
  { label: "Florianópolis — 28 Mar 2004", file: "fig_TS_event_009_florianopolis_20040328.png", sector: "South", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Florianópolis — 13 Mai 2010", file: "fig_TS_event_014_florianopolis_20100513.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Florianópolis — 24 Jun 2010", file: "fig_TS_event_018_florianopolis_20100624.png", sector: "Central", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Florianópolis — 16 Jul 2010", file: "fig_TS_event_019_florianopolis_20100716.png", sector: "Central", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Florianópolis — 15 Set 2016", file: "fig_TS_event_032_florianopolis_20160915.png", sector: "Central-north", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Florianópolis — 22 Mai 2017", file: "fig_TS_event_038_florianopolis_20170522.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Florianópolis — 13 Set 2017", file: "fig_TS_event_043_florianopolis_20170913.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Florianópolis — 04 Abr 2020", file: "fig_TS_event_073_florianopolis_20200404.png", sector: "Central-north", isConcurrentSsh: true, isConcurrentTotal: true, detectionChange: "maintained" },
  { label: "Garopaba — 09 Jun 2010", file: "fig_TS_event_017_garopaba_20100609.png", sector: "South", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Garopaba — 01 Out 2017", file: "fig_TS_event_047_garopaba_20171001.png", sector: "Central-south", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Itajaí — 08 Ago 2005", file: "fig_TS_event_010_itajai_20050808.png", sector: "Central-north", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Itajaí — 24 Abr 2006", file: "fig_TS_event_012_itajai_20060424.png", sector: "Central-north", isConcurrentSsh: true, isConcurrentTotal: true, detectionChange: "maintained" },
  { label: "Itapema — 30 Set 2017", file: "fig_TS_event_046_itapema_20170930.png", sector: "Central-north", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Itapoá — 10 Ago 2000", file: "fig_TS_event_003_itapoa_20000810.png", sector: "North", isConcurrentSsh: true, isConcurrentTotal: true, detectionChange: "maintained" },
  { label: "Itapoá — 05 Mai 2001", file: "fig_TS_event_004_itapoa_20010505.png", sector: "North", isConcurrentSsh: true, isConcurrentTotal: false, detectionChange: "lost" },
  { label: "Itapoá — 15 Ago 2017", file: "fig_TS_event_039_itapoa_20170815.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Itapoá — 21 Mai 2018", file: "fig_TS_event_053_itapoa_20180521.png", sector: "North", isConcurrentSsh: true, isConcurrentTotal: true, detectionChange: "maintained" },
  { label: "Itapoá — 15 Jun 2018", file: "fig_TS_event_054_itapoa_20180615.png", sector: "North", isConcurrentSsh: true, isConcurrentTotal: false, detectionChange: "lost" },
  { label: "Itapoá — 19 Set 2018", file: "fig_TS_event_057_itapoa_20180919.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Itapoá — 08 Out 2018", file: "fig_TS_event_058_itapoa_20181008.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Itapoá — 21 Jul 2019", file: "fig_TS_event_064_itapoa_20190721.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Itapoá — 04 Ago 2019", file: "fig_TS_event_067_itapoa_20190804.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Itapoá — 09 Abr 2020", file: "fig_TS_event_075_itapoa_20200409.png", sector: "North", isConcurrentSsh: true, isConcurrentTotal: false, detectionChange: "lost" },
  { label: "Içara/Balneário Rincão — 27 Mar 2004", file: "fig_TS_event_008_icara_balneario_rincao_20040327.png", sector: "South", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Navegantes — 06 Mai 2001", file: "fig_TS_event_005_navegantes_20010506.png", sector: "North", isConcurrentSsh: true, isConcurrentTotal: false, detectionChange: "lost" },
  { label: "Navegantes — 01 Jun 2010", file: "fig_TS_event_016_navegantes_20100601.png", sector: "Central-north", isConcurrentSsh: true, isConcurrentTotal: true, detectionChange: "maintained" },
  { label: "Navegantes — 03 Mai 2011", file: "fig_TS_event_025_navegantes_20110503.png", sector: "Central-north", isConcurrentSsh: true, isConcurrentTotal: false, detectionChange: "lost" },
  { label: "Navegantes — 07 Set 2017", file: "fig_TS_event_041_navegantes_20170907.png", sector: "Central-north", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Navegantes — 16 Set 2017", file: "fig_TS_event_044_navegantes_20170916.png", sector: "Central-north", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Navegantes — 19 Set 2019", file: "fig_TS_event_069_navegantes_20190919.png", sector: "Central-north", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Palhoça — 09 Ago 2005", file: "fig_TS_event_011_palhoca_20050809.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Passo de Torres — 28 Mar 2004", file: "fig_TS_event_009_passo_de_torres_20040328.png", sector: "South", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Penha — 04 Jun 2011", file: "fig_TS_event_027_penha_20110604.png", sector: "Central-north", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Porto Belo — 15 Set 2016", file: "fig_TS_event_032_porto_belo_20160915.png", sector: "Central-north", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "Porto Belo — 14 Abr 2018", file: "fig_TS_event_052_porto_belo_20180414.png", sector: "Central-north", isConcurrentSsh: true, isConcurrentTotal: false, detectionChange: "lost" },
  { label: "Porto Belo — 04 Abr 2020", file: "fig_TS_event_073_porto_belo_20200404.png", sector: "Central-north", isConcurrentSsh: true, isConcurrentTotal: true, detectionChange: "maintained" },
  { label: "Porto Belo — 08 Abr 2020", file: "fig_TS_event_074_porto_belo_20200408.png", sector: "South", isConcurrentSsh: true, isConcurrentTotal: false, detectionChange: "lost" },
  { label: "São Francisco do Sul — 15 Fev 1998", file: "fig_TS_event_001_sao_francisco_do_sul_19980215.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "São Francisco do Sul — 07 Out 2017", file: "fig_TS_event_048_sao_francisco_do_sul_20171007.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "São Francisco do Sul — 11 Dez 2017", file: "fig_TS_event_050_sao_francisco_do_sul_20171211.png", sector: "North", isConcurrentSsh: false, isConcurrentTotal: false, detectionChange: "neither" },
  { label: "São Francisco do Sul — 15 Ago 2019", file: "fig_TS_event_068_sao_francisco_do_sul_20190815.png", sector: "North", isConcurrentSsh: true, isConcurrentTotal: true, detectionChange: "maintained" },
] as const;
export type TsEvent = typeof tsEvents[number];